# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Application(object):
    def setupUi(self, Application):
        Application.setObjectName("Application")
        Application.resize(1000, 800)
        Application.setMinimumSize(QtCore.QSize(1000, 800))
        Application.setMaximumSize(QtCore.QSize(1000, 800))
        Application.setMouseTracking(True)
        Application.setStyleSheet("background-color:rgb(32, 38, 52);")
        Application.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Application)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setStyleSheet("background-color:rgb(32, 38, 52);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textEdit_GeneratedText = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_GeneratedText.setMinimumSize(QtCore.QSize(980, 630))
        self.textEdit_GeneratedText.setMaximumSize(QtCore.QSize(980, 630))
        self.textEdit_GeneratedText.setStyleSheet("background-color: rgb(56, 64, 85);\n"
"color:white")
        self.textEdit_GeneratedText.setObjectName("textEdit_GeneratedText")
        self.verticalLayout.addWidget(self.textEdit_GeneratedText)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("color:white")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.comboBox_model = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_model.setMinimumSize(QtCore.QSize(140, 25))
        self.comboBox_model.setMaximumSize(QtCore.QSize(140, 25))
        self.comboBox_model.setStyleSheet("QComboBox {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:white;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView { color: white; }\n"
"\n"
"QComboBox:disabled {\n"
"    border-radius: 4px;\n"
"    background-color:rgb(83, 89, 110);\n"
"    color:rgb(200, 200, 200);\n"
"    border: 0px solid black;\n"
"}")
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_model)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("color:white")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.lineEdit_length = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_length.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit_length.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_length.setStyleSheet("background-color: rgb(56, 64, 85);\n"
"color: white;")
        self.lineEdit_length.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_length.setObjectName("lineEdit_length")
        self.horizontalLayout_3.addWidget(self.lineEdit_length)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_clear = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_clear.setMinimumSize(QtCore.QSize(120, 45))
        self.toolButton_clear.setMaximumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toolButton_clear.setFont(font)
        self.toolButton_clear.setStyleSheet("QToolButton {\n"
"    color:white; \n"
"    background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0,         stop:0 rgba(32, 38, 52, 255), \n"
"        stop:1 rgba(91, 99, 120, 255));\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"}")
        self.toolButton_clear.setObjectName("toolButton_clear")
        self.horizontalLayout_4.addWidget(self.toolButton_clear)
        self.toolButton_process = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_process.setMinimumSize(QtCore.QSize(120, 45))
        self.toolButton_process.setMaximumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.toolButton_process.setFont(font)
        self.toolButton_process.setStyleSheet("QToolButton {\n"
"    color:white; \n"
"    background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0,         stop:0 rgba(32, 38, 52, 255), \n"
"        stop:1 rgba(91, 99, 120, 255));\n"
"    border: 2px solid black;\n"
"    border-radius: 8px;\n"
"}")
        self.toolButton_process.setObjectName("toolButton_process")
        self.horizontalLayout_4.addWidget(self.toolButton_process)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        Application.setCentralWidget(self.centralwidget)

        self.retranslateUi(Application)
        QtCore.QMetaObject.connectSlotsByName(Application)

    def retranslateUi(self, Application):
        _translate = QtCore.QCoreApplication.translate
        Application.setWindowTitle(_translate("Application", "MainWindow"))
        self.label_3.setText(_translate("Application", "Text"))
        self.label_6.setText(_translate("Application", "Model"))
        self.comboBox_model.setItemText(0, _translate("Application", "GPT2"))
        self.label_7.setText(_translate("Application", "Generated Length"))
        self.lineEdit_length.setText(_translate("Application", "256"))
        self.toolButton_clear.setText(_translate("Application", "Clear"))
        self.toolButton_process.setText(_translate("Application", "Process"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Application = QtWidgets.QMainWindow()
    ui = Ui_Application()
    ui.setupUi(Application)
    Application.show()
    sys.exit(app.exec_())
